"""
Hypothesis Selection Screen Module
Interactive modal for selecting and editing hypotheses generated by LLM.
Displays hypotheses with priority, edit capabilities, and custom additions.

사용자 정렬(Step 9)을 위한 가설 선택 화면.

bi_agent_console.py와의 통합:
1. 임포트: from backend.orchestrator.screens.hypothesis_screen import HypothesisScreen, Hypothesis
2. 화면 푸시: self.push_screen(HypothesisScreen(hypotheses, on_confirm_callback))
3. 콜백 처리: def on_confirm_callback(selected_hypotheses: List[Hypothesis]): ...
"""

from typing import List, Callable, Optional
from dataclasses import dataclass, field
from enum import Enum

from textual.screen import ModalScreen
from textual.app import ComposeResult
from textual.widgets import Static, OptionList, Input, Label, Button
from textual.widgets.option_list import Option
from textual.containers import Container, Vertical, Horizontal, VerticalScroll
from textual.binding import Binding
from rich.text import Text

from backend.utils.logger_setup import setup_logger

logger = setup_logger("hypothesis_screen", "hypothesis_screen.log")


class HypothesisSource(Enum):
    """Source of hypothesis generation"""
    LLM = "llm"
    TEMPLATE = "template"
    CUSTOM = "custom"


@dataclass
class Hypothesis:
    """
    Data structure for a hypothesis.

    Attributes:
        id: Unique identifier
        text: Hypothesis text content
        priority: Priority level (0-10, higher is more important)
        selected: Whether this hypothesis is selected for analysis
        edited: Whether the text has been edited by user
        source: Origin of the hypothesis (LLM, template, custom)
    """
    id: str
    text: str
    priority: int = 0
    selected: bool = True
    edited: bool = False
    source: str = "llm"

    def __post_init__(self):
        """Validate hypothesis data after initialization."""
        if self.priority < 0 or self.priority > 10:
            self.priority = max(0, min(10, self.priority))


@dataclass
class HypothesisSelectionResult:
    """Result of hypothesis selection operation"""
    selected_hypotheses: List[Hypothesis]
    all_hypotheses: List[Hypothesis]
    cancelled: bool = False


class HypothesisScreen(ModalScreen[HypothesisSelectionResult]):
    """
    Modal screen for interactive hypothesis selection and editing.

    Features:
    - Multi-select with checkbox display
    - Edit hypothesis text inline
    - Set priority (0-10)
    - Add custom hypotheses
    - Color-coded priority levels
    - Source indicators (LLM, Template, Custom)
    - Y/N/E/Space keyboard shortcuts
    - Real-time preview of changes

    Usage:
        result = await self.app.push_screen_wait(
            HypothesisScreen(hypotheses, callback)
        )
        if not result.cancelled:
            selected = result.selected_hypotheses
    """

    CSS = """
    HypothesisScreen {
        align: center middle;
        background: rgba(0, 0, 0, 0.85);
    }

    #hypothesis-modal {
        width: 90%;
        max-width: 120;
        height: 85%;
        background: #1a1b1e;
        border: thick #7c3aed;
        padding: 1;
    }

    #modal-title {
        text-align: center;
        color: #f8fafc;
        text-style: bold;
        background: #7c3aed;
        padding: 1;
        margin-bottom: 1;
    }

    #main-layout {
        width: 100%;
        height: 1fr;
        layout: horizontal;
    }

    #left-panel {
        width: 55%;
        height: 100%;
        border-right: solid #2d2f34;
        padding-right: 1;
    }

    #right-panel {
        width: 45%;
        height: 100%;
        padding-left: 1;
    }

    #hypothesis-list {
        height: 1fr;
        background: #111214;
        border: solid #2d2f34;
        margin-bottom: 1;
    }

    .option-list--option-highlighted {
        background: #7c3aed;
        color: #f8fafc;
    }

    #edit-container {
        height: auto;
        margin-top: 1;
        padding: 1;
        background: #111214;
        border: solid #2d2f34;
    }

    #edit-input {
        width: 100%;
        background: #1a1b1e;
        border: solid #404040;
        color: #f8fafc;
        margin-bottom: 1;
    }

    #edit-input:focus {
        border: solid #7c3aed;
    }

    #priority-container {
        height: auto;
        margin-top: 1;
    }

    #priority-input {
        width: 15;
        background: #1a1b1e;
        border: solid #404040;
        color: #f8fafc;
    }

    #priority-input:focus {
        border: solid #7c3aed;
    }

    #add-container {
        height: auto;
        margin-top: 1;
        padding: 1;
        background: #111214;
        border: solid #2d2f34;
    }

    #add-input {
        width: 100%;
        background: #1a1b1e;
        border: solid #404040;
        color: #f8fafc;
        margin-bottom: 1;
    }

    #add-input:focus {
        border: solid #10b981;
    }

    #detail-panel {
        height: 1fr;
        background: #111214;
        border: solid #2d2f34;
        padding: 1;
    }

    .detail-section {
        margin-bottom: 1;
    }

    .section-label {
        color: #94a3b8;
        text-style: bold;
        margin-bottom: 0;
    }

    .section-content {
        color: #f8fafc;
        margin-left: 2;
    }

    .priority-high {
        color: #ef4444;
        text-style: bold;
    }

    .priority-medium {
        color: #f59e0b;
        text-style: bold;
    }

    .priority-low {
        color: #6b7280;
    }

    #button-bar {
        height: auto;
        layout: horizontal;
        align: center middle;
        margin-top: 1;
    }

    #confirm-btn {
        background: #10b981;
        color: white;
        margin-right: 2;
        min-width: 16;
    }

    #confirm-btn:hover {
        background: #059669;
    }

    #cancel-btn {
        background: #6b7280;
        color: white;
        min-width: 16;
    }

    #cancel-btn:hover {
        background: #4b5563;
    }

    #add-btn {
        background: #7c3aed;
        color: white;
        width: 100%;
    }

    #add-btn:hover {
        background: #6d28d9;
    }

    #save-edit-btn {
        background: #10b981;
        color: white;
        width: 100%;
    }

    #save-edit-btn:hover {
        background: #059669;
    }

    #selection-counter {
        color: #7c3aed;
        text-align: center;
        margin-top: 1;
    }

    .source-llm {
        color: #3b82f6;
    }

    .source-template {
        color: #8b5cf6;
    }

    .source-custom {
        color: #10b981;
    }

    .edited-indicator {
        color: #f59e0b;
    }
    """

    BINDINGS = [
        Binding("y", "confirm", "Confirm Selection", show=True),
        Binding("n,escape", "cancel", "Cancel", show=True),
        Binding("space", "toggle", "Toggle Selection", show=True),
        Binding("e", "edit", "Edit Selected", show=True),
        Binding("p", "set_priority", "Set Priority", show=True),
        Binding("a", "add_custom", "Add Custom", show=True),
        Binding("s", "save_edit", "Save Edit", show=False),
    ]

    def __init__(
        self,
        hypotheses: List[Hypothesis],
        callback: Optional[Callable[[List[Hypothesis]], None]] = None
    ):
        """
        Initialize hypothesis selection screen.

        Args:
            hypotheses: List of Hypothesis objects generated by LLM
            callback: Optional callback function(selected_hypotheses: List[Hypothesis])
        """
        super().__init__()
        self.hypotheses = hypotheses.copy()
        self.callback = callback
        self.editing_mode = False
        self.priority_mode = False
        self.add_mode = False
        self.next_id = len(hypotheses) + 1

        logger.info(f"HypothesisScreen initialized with {len(hypotheses)} hypotheses")

    def compose(self) -> ComposeResult:
        """Compose the UI layout."""
        with Container(id="hypothesis-modal"):
            yield Label("💡 Hypothesis Selection - Choose and Edit Hypotheses", id="modal-title")

            with Horizontal(id="main-layout"):
                # Left Panel: Hypothesis List
                with Vertical(id="left-panel"):
                    yield Label(
                        "[dim]Space: Toggle | E: Edit | P: Priority | A: Add Custom | Y: Confirm | N: Cancel[/dim]"
                    )

                    yield OptionList(id="hypothesis-list")

                    yield Label(
                        "0 hypotheses selected",
                        id="selection-counter"
                    )

                    # Edit Container (hidden by default)
                    with Vertical(id="edit-container") as edit_container:
                        yield Label("📝 Edit Hypothesis:", classes="section-label")
                        yield Input(
                            id="edit-input",
                            placeholder="가설 내용을 수정하세요..."
                        )
                        yield Button("💾 Save Edit (S)", id="save-edit-btn")

                    # Priority Container (hidden by default)
                    with Horizontal(id="priority-container") as priority_container:
                        yield Label("⭐ Priority (0-10):", classes="section-label")
                        yield Input(
                            id="priority-input",
                            placeholder="0-10",
                            max_length=2
                        )

                    # Add Custom Container (hidden by default)
                    with Vertical(id="add-container") as add_container:
                        yield Label("➕ Add Custom Hypothesis:", classes="section-label")
                        yield Input(
                            id="add-input",
                            placeholder="새로운 가설을 입력하세요..."
                        )
                        yield Button("➕ Add to List", id="add-btn")

                # Right Panel: Details
                with Vertical(id="right-panel"):
                    yield VerticalScroll(
                        Static("Select a hypothesis to view details", id="detail-content"),
                        id="detail-panel"
                    )

            # Button Bar
            with Horizontal(id="button-bar"):
                yield Button("✓ Confirm (Y)", id="confirm-btn", variant="success")
                yield Button("✗ Cancel (N)", id="cancel-btn", variant="default")

    def on_mount(self) -> None:
        """Populate hypothesis list on mount."""
        self._populate_hypothesis_list()
        self._update_selection_counter()
        self._hide_all_edit_modes()

        # Focus on hypothesis list initially
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)
        hypothesis_list.focus()

        logger.info("HypothesisScreen mounted successfully")

    def _hide_all_edit_modes(self) -> None:
        """Hide all editing containers."""
        self.query_one("#edit-container").display = False
        self.query_one("#priority-container").display = False
        self.query_one("#add-container").display = False
        self.editing_mode = False
        self.priority_mode = False
        self.add_mode = False

    def _populate_hypothesis_list(self) -> None:
        """Populate the hypothesis list with formatted options."""
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)
        hypothesis_list.clear_options()

        for idx, hyp in enumerate(self.hypotheses):
            # Build formatted option text
            checkbox = "☑" if hyp.selected else "☐"

            # Priority indicator
            if hyp.priority >= 8:
                priority_text = f"[bold red]P{hyp.priority}[/bold red]"
            elif hyp.priority >= 5:
                priority_text = f"[bold yellow]P{hyp.priority}[/bold yellow]"
            elif hyp.priority > 0:
                priority_text = f"[dim]P{hyp.priority}[/dim]"
            else:
                priority_text = "  "

            # Source indicator
            source_colors = {
                "llm": "blue",
                "template": "magenta",
                "custom": "green"
            }
            source_color = source_colors.get(hyp.source, "white")
            source_badge = f"[{source_color}]{hyp.source.upper()}[/{source_color}]"

            # Edited indicator
            edited_badge = "[yellow]✎[/yellow]" if hyp.edited else ""

            # Truncate long text
            display_text = hyp.text[:80] + "..." if len(hyp.text) > 80 else hyp.text

            option_text = f"{checkbox} {priority_text} {source_badge} {edited_badge} {display_text}"

            hypothesis_list.add_option(
                Option(
                    option_text,
                    id=hyp.id
                )
            )

        # Auto-select first item if available
        if hypothesis_list.option_count > 0:
            hypothesis_list.highlighted = 0
            self._show_hypothesis_details(self.hypotheses[0])

    def _get_priority_color(self, priority: int) -> str:
        """Get color for priority level."""
        if priority >= 8:
            return "red"
        elif priority >= 5:
            return "yellow"
        else:
            return "#6b7280"

    def _show_hypothesis_details(self, hypothesis: Hypothesis) -> None:
        """Display detailed information for selected hypothesis."""
        detail_content = self.query_one("#detail-content", Static)

        # Build rich content
        content = Text()

        # Hypothesis ID
        content.append(f"🆔 Hypothesis #{hypothesis.id}\n", style="bold cyan")
        content.append("\n")

        # Priority
        priority_style = self._get_priority_color(hypothesis.priority)
        content.append("Priority: ", style="dim")
        content.append(f"{hypothesis.priority}/10", style=priority_style)
        if hypothesis.priority >= 8:
            content.append(" (HIGH)", style="bold red")
        elif hypothesis.priority >= 5:
            content.append(" (MEDIUM)", style="bold yellow")
        content.append("\n\n")

        # Source
        source_styles = {
            "llm": "blue",
            "template": "magenta",
            "custom": "green"
        }
        source_style = source_styles.get(hypothesis.source, "white")
        content.append("Source: ", style="dim")
        content.append(f"{hypothesis.source.upper()}\n", style=source_style)
        content.append("\n")

        # Edited status
        if hypothesis.edited:
            content.append("✎ EDITED BY USER\n", style="bold yellow")
            content.append("\n")

        # Hypothesis text
        content.append("💡 Hypothesis:\n", style="bold")
        content.append(f"{hypothesis.text}\n", style="")
        content.append("\n")

        # Selection status
        if hypothesis.selected:
            content.append("✓ Currently Selected\n", style="bold green")
        else:
            content.append("☐ Not Selected\n", style="dim")

        content.append("\n[dim]")
        content.append("Press Space to toggle selection\n")
        content.append("Press E to edit text\n")
        content.append("Press P to set priority[/dim]")

        detail_content.update(content)

    def on_option_list_option_highlighted(self, event: OptionList.OptionHighlighted) -> None:
        """Update details panel when option is highlighted."""
        if event.option and event.option.id:
            hypothesis_id = str(event.option.id)

            # Find hypothesis
            for hyp in self.hypotheses:
                if hyp.id == hypothesis_id:
                    self._show_hypothesis_details(hyp)
                    break

    def action_toggle(self) -> None:
        """Toggle selection of highlighted hypothesis."""
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)

        if hypothesis_list.highlighted is not None:
            option = hypothesis_list.get_option_at_index(hypothesis_list.highlighted)
            if option and option.id:
                hypothesis_id = str(option.id)

                # Find and toggle
                for hyp in self.hypotheses:
                    if hyp.id == hypothesis_id:
                        hyp.selected = not hyp.selected
                        logger.debug(f"Toggled hypothesis {hypothesis_id}: selected={hyp.selected}")
                        break

                # Refresh display
                current_idx = hypothesis_list.highlighted
                self._populate_hypothesis_list()
                self._update_selection_counter()

                # Restore highlight
                hypothesis_list.highlighted = current_idx

                # Update detail panel
                for hyp in self.hypotheses:
                    if hyp.id == hypothesis_id:
                        self._show_hypothesis_details(hyp)
                        break

    def action_edit(self) -> None:
        """Show edit input for selected hypothesis."""
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)

        if hypothesis_list.highlighted is None:
            self.app.notify("⚠️ No hypothesis selected", severity="warning")
            return

        option = hypothesis_list.get_option_at_index(hypothesis_list.highlighted)
        if not option or not option.id:
            return

        hypothesis_id = str(option.id)

        # Find hypothesis
        for hyp in self.hypotheses:
            if hyp.id == hypothesis_id:
                # Show edit container
                self._hide_all_edit_modes()
                edit_container = self.query_one("#edit-container")
                edit_container.display = True
                self.editing_mode = True

                # Populate edit input
                edit_input = self.query_one("#edit-input", Input)
                edit_input.value = hyp.text
                edit_input.focus()

                logger.debug(f"Editing hypothesis {hypothesis_id}")
                break

    def action_save_edit(self) -> None:
        """Save edited hypothesis text."""
        if not self.editing_mode:
            return

        hypothesis_list = self.query_one("#hypothesis-list", OptionList)
        edit_input = self.query_one("#edit-input", Input)

        if hypothesis_list.highlighted is None:
            return

        option = hypothesis_list.get_option_at_index(hypothesis_list.highlighted)
        if not option or not option.id:
            return

        hypothesis_id = str(option.id)
        new_text = edit_input.value.strip()

        if not new_text:
            self.app.notify("⚠️ Hypothesis text cannot be empty", severity="warning")
            return

        # Update hypothesis
        for hyp in self.hypotheses:
            if hyp.id == hypothesis_id:
                old_text = hyp.text
                hyp.text = new_text
                hyp.edited = True
                logger.info(f"Updated hypothesis {hypothesis_id}: '{old_text}' -> '{new_text}'")
                break

        # Refresh display
        current_idx = hypothesis_list.highlighted
        self._populate_hypothesis_list()
        hypothesis_list.highlighted = current_idx

        # Hide edit container
        self._hide_all_edit_modes()
        hypothesis_list.focus()

        self.app.notify("✓ Hypothesis updated", severity="information")

        # Update detail panel
        for hyp in self.hypotheses:
            if hyp.id == hypothesis_id:
                self._show_hypothesis_details(hyp)
                break

    def action_set_priority(self) -> None:
        """Show priority input for selected hypothesis."""
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)

        if hypothesis_list.highlighted is None:
            self.app.notify("⚠️ No hypothesis selected", severity="warning")
            return

        # Show priority container
        self._hide_all_edit_modes()
        priority_container = self.query_one("#priority-container")
        priority_container.display = True
        self.priority_mode = True

        # Focus priority input
        priority_input = self.query_one("#priority-input", Input)

        # Pre-populate with current priority
        option = hypothesis_list.get_option_at_index(hypothesis_list.highlighted)
        if option and option.id:
            for hyp in self.hypotheses:
                if hyp.id == str(option.id):
                    priority_input.value = str(hyp.priority)
                    break

        priority_input.focus()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        """Handle input submission (Enter key)."""
        if event.input.id == "priority-input":
            self._save_priority()
        elif event.input.id == "add-input":
            self._add_custom_hypothesis()
        elif event.input.id == "edit-input":
            self.action_save_edit()

    def _save_priority(self) -> None:
        """Save priority value for selected hypothesis."""
        if not self.priority_mode:
            return

        hypothesis_list = self.query_one("#hypothesis-list", OptionList)
        priority_input = self.query_one("#priority-input", Input)

        if hypothesis_list.highlighted is None:
            return

        option = hypothesis_list.get_option_at_index(hypothesis_list.highlighted)
        if not option or not option.id:
            return

        hypothesis_id = str(option.id)

        # Validate priority
        try:
            priority = int(priority_input.value.strip())
            if priority < 0 or priority > 10:
                self.app.notify("⚠️ Priority must be between 0 and 10", severity="warning")
                return
        except ValueError:
            self.app.notify("⚠️ Invalid priority value", severity="warning")
            return

        # Update hypothesis
        for hyp in self.hypotheses:
            if hyp.id == hypothesis_id:
                old_priority = hyp.priority
                hyp.priority = priority
                logger.info(f"Updated priority for hypothesis {hypothesis_id}: {old_priority} -> {priority}")
                break

        # Refresh display
        current_idx = hypothesis_list.highlighted
        self._populate_hypothesis_list()
        hypothesis_list.highlighted = current_idx

        # Hide priority container
        self._hide_all_edit_modes()
        hypothesis_list.focus()

        self.app.notify(f"✓ Priority set to {priority}", severity="information")

        # Update detail panel
        for hyp in self.hypotheses:
            if hyp.id == hypothesis_id:
                self._show_hypothesis_details(hyp)
                break

    def action_add_custom(self) -> None:
        """Show input for adding custom hypothesis."""
        self._hide_all_edit_modes()
        add_container = self.query_one("#add-container")
        add_container.display = True
        self.add_mode = True

        add_input = self.query_one("#add-input", Input)
        add_input.value = ""
        add_input.focus()

    def _add_custom_hypothesis(self) -> None:
        """Add new custom hypothesis to the list."""
        if not self.add_mode:
            return

        add_input = self.query_one("#add-input", Input)
        text = add_input.value.strip()

        if not text:
            self.app.notify("⚠️ Hypothesis text cannot be empty", severity="warning")
            return

        # Create new hypothesis
        new_hyp = Hypothesis(
            id=f"custom_{self.next_id}",
            text=text,
            priority=5,  # Default medium priority
            selected=True,
            edited=False,
            source="custom"
        )

        self.hypotheses.append(new_hyp)
        self.next_id += 1

        logger.info(f"Added custom hypothesis: {new_hyp.id}")

        # Refresh display
        hypothesis_list = self.query_one("#hypothesis-list", OptionList)
        self._populate_hypothesis_list()
        self._update_selection_counter()

        # Highlight new item
        hypothesis_list.highlighted = len(self.hypotheses) - 1

        # Hide add container
        self._hide_all_edit_modes()
        hypothesis_list.focus()

        self.app.notify("✓ Custom hypothesis added", severity="information")

        # Show details for new hypothesis
        self._show_hypothesis_details(new_hyp)

    def _update_selection_counter(self) -> None:
        """Update the selection counter label."""
        counter = self.query_one("#selection-counter", Label)
        count = sum(1 for hyp in self.hypotheses if hyp.selected)

        if count == 0:
            counter.update("No hypotheses selected")
        elif count == 1:
            counter.update(f"[bold]{count}[/bold] hypothesis selected")
        else:
            counter.update(f"[bold]{count}[/bold] hypotheses selected")

    def action_confirm(self) -> None:
        """Confirm selection and dismiss screen."""
        selected = [hyp for hyp in self.hypotheses if hyp.selected]

        if not selected:
            self.app.notify(
                "⚠️ No hypotheses selected. Please select at least one hypothesis.",
                severity="warning",
                timeout=3
            )
            return

        # Sort by priority (descending)
        selected.sort(key=lambda h: h.priority, reverse=True)

        logger.info(f"User confirmed selection: {len(selected)} hypotheses")
        for hyp in selected:
            logger.debug(f"  - {hyp.id}: P{hyp.priority} - {hyp.text[:50]}...")

        result = HypothesisSelectionResult(
            selected_hypotheses=selected,
            all_hypotheses=self.hypotheses,
            cancelled=False
        )

        # Call callback if provided
        if self.callback:
            self.callback(selected)

        self.dismiss(result)

    def action_cancel(self) -> None:
        """Cancel and dismiss screen."""
        logger.info("User cancelled hypothesis selection")

        result = HypothesisSelectionResult(
            selected_hypotheses=[],
            all_hypotheses=self.hypotheses,
            cancelled=True
        )

        self.dismiss(result)

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button clicks."""
        if event.button.id == "confirm-btn":
            self.action_confirm()
        elif event.button.id == "cancel-btn":
            self.action_cancel()
        elif event.button.id == "add-btn":
            self._add_custom_hypothesis()
        elif event.button.id == "save-edit-btn":
            self.action_save_edit()
