from typing import Protocol, Any, Dict, List, Optional
from textual.app import App

class HandlerContext(Protocol):
    """
    Handler가 App의 기능을 사용할 수 있도록 추상화된 컨텍스트 인터페이스
    """
    @property
    def app(self) -> App: ...
    
    def query_one(self, selector: str, expect_type: type = None) -> Any: ...
    def push_screen(self, screen: Any, callback: Any = None) -> None: ...
    def notify(self, message: str, severity: str = "information") -> None: ...
    async def handle_command(self, cmd_text: str) -> None: ...
    
    # 필요한 추가 메서드들
    def refresh(self) -> None: ...
    def call_after_refresh(self, func: Any, *args, **kwargs) -> None: ...

class CommandHandlerProtocol(Protocol):
    """
    슬래시 명령어 처리를 위한 인터페이스
    """
    async def handle(self, cmd_text: str) -> None: ...
    def can_handle(self, cmd: str) -> bool: ...

class InputHandlerProtocol(Protocol):
    """
    키보드 입력 처리를 위한 인터페이스
    """
    async def handle_key(self, event: Any) -> bool: ...
